### ISSUE TITLE
search_form set to null

### ISSUE THREAD

**Issue by jmaquet** [marmelab/SonataElasticaBundle#13]
I had this issue while using the bundle :
```
ContextErrorException: Catchable Fatal Error: Argument 5 passed to Marmelab\SonataElasticaBundle\Builder\ElasticaDatagridBuilder::__construct() must be an instance of Symfony\Component\Form\AbstractType, null given
```

After analyze i saw this line in DependencyInjection/AdminTagElasticaCompilerPass.php : 
```
$searchForm = isset($attributes['search_form']) ? new Reference($attributes['search_form']) : null;
$datagridService = $this->createDatagridService($container, $id, $ormGuesserService, $proxyRepositoryService, $searchForm);
```

Whereas the construct of ElasticaDatagridBuilder does not support a null value for $searchForm

I think the null value for the tag search_form should be managed as null everywhere.

**Comment by jmaquet** [comment]
For information here is a way to fix this for now : 
```yml
# Acme/Resources/config/services.yml
    admin.product:
        class: Acme\Admin\ProductAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "admin.group.product"
              label: "admin.model.product"
              label_catalogue: "AcmeBundle"
              fastGrid: true
              searcher: "elastica"
              search_index: "acme.Product"
              search_form: "acme.form.type.search"
        arguments:
            - ~
            - Acme\Entity\Product
            - ~
            - ~

    acme.form.type.search:
        class: Acme\Form\Type\searchType
        tags:
            - { name: form.type, alias: search }
```
And i created a dummy form type for search.
```php
// Acme\Form\Type
namespace Acme\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('search');
    }

    public function getName()
    {
        return 'search';
    }
}
```
