### ISSUE TITLE
Forgot something in the documentation?

### ISSUE THREAD

**Issue by vgross** [marmelab/SonataElasticaBundle#3]
I try your bundle today but after done all that you write in the documentation, my list page doesn't use elasticsearch? I try to turn off elasticsearch to make sure.

here my service : 

```
report.daily_snapshot:
    class: XXX\ReportBundle\Admin\DailySnapshotAdmin
    tags:
    - { name: sonata.admin, manager_type: orm,  transformer:"marmelab.book.elastica.transformer" , label: "Snapshots", searcher:"elastica", search_index:"website.daily" } 
    arguments: [null,  XXX\ReportBundle\Entity\DailySnapshot, SonataAdminBundle:CRUD, '@fos_elastica.finder.website.daily'] 
```

I extend my admin class with ElasticaAdmin as well.

something wrong?
